name: probando evns

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=\":America/Mexico_City\" date +\"%Y-%m-%d\")"
    - name: probando
      run: |
        echo "Actualización de ${{steps.date.outputs.date}}}"
