name: probando evns

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: probando
      run: |
        export HOY=TZ=":America/Mexico_City" date +"%Y-%m-%d"
        echo "Actualización de ${HOY}"
